# Generated by Django 5.1.4 on 2025-02-22 17:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=400)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('gcse', 'GCSE'), ('alevel', 'A Level')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Expertise Area')),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tutor Name')),
                ('about', models.TextField(blank=True, max_length=2000)),
                ('summary', models.CharField(blank=True, help_text='Enter a short summary (max 500 characters).', max_length=500, verbose_name='Short Summary')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutors/', verbose_name='Profile Image')),
                ('expertise', models.ManyToManyField(blank=True, related_name='tutors', to='home.expertise', verbose_name='Areas of Expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.tutor')),
            ],
        ),
    ]
