# Generated by Django 5.1.4 on 2025-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tutor',
        ),
        migrations.AddField(
            model_name='tutor',
            name='qualifications',
            field=models.TextField(blank=True, help_text='List the tutor’s qualifications (comma-separated or free text).', max_length=500, verbose_name='Qualifications'),
        ),
    ]
