# Generated by Django 5.1.4 on 2025-06-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_review_tutor_tutor_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='home.tutor', verbose_name='Tutor'),
        ),
    ]
