# Generated by Django 5.1.4 on 2025-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='review',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
