# Generated by Django 5.1.4 on 2025-01-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tutor_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='paragraph',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
