# Generated by Django 5.1.4 on 2025-01-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homecontent_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='hourly_rate',
        ),
    ]
