# Generated by Django 5.1.4 on 2025-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_tutor_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='about',
            field=models.CharField(max_length=200),
        ),
    ]
