# Generated by Django 5.1.4 on 2025-02-22 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Expertise Area')),
            ],
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='photo',
        ),
        migrations.AddField(
            model_name='tutor',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tutor Biography'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='level',
            field=models.CharField(choices=[('gcse', 'GCSE'), ('alevel', 'A Level')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='expertise',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tutor Name'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='home.expertise', verbose_name='Areas of Expertise'),
        ),
    ]
