# .github/workflows/deploy.yml
name: Build and deploy – HillTop Tuition

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
# ───────────────────────────────────── build ───────────────────────────────────
  build:
    runs-on: ubuntu-latest            

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create venv & install deps
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Login so collectstatic can push to Blob Storage via the UAMI
    - name: Azure login (build job)
      uses: azure/login@v2
      with:
        client-id:      ${{ secrets.CLIENTID }}
        tenant-id:      ${{ secrets.TENANTID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}
    - name: Collect static files
      run: |
        source venv/bin/activate
        python manage.py collectstatic --noinput
      env:
        AZURE_DEPLOYED: 'true'
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

    - name: Zip artifact
      run: zip release.zip ./* -r

    - uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          release.zip
          !venv/

# ───────────────────────────────────── deploy ──────────────────────────────────
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-app

    - run: unzip release.zip

    - name: Azure login (deploy job)
      uses: azure/login@v2
      with:
        client-id:      ${{ secrets.CLIENTID }}
        tenant-id:      ${{ secrets.TENANTID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}

    - name: Deploy to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name:           WA-Hilltop-Tuition-27042025
        resource-group-name: RG-Hilltop-Tuition-27042025
