# .github/workflows/deploy.yml
name: Build and deploy – HillTop Tuition

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write          # for azure/login
  contents:  read          # checkout needs this

jobs:
# ──────────────────────────────── deploy ────────────────────────────────
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install deps (collectstatic only)
      run: |
        python -m pip install --upgrade pip
        pip  install -r requirements.txt

    - name: Azure login (collectstatic)
      uses: azure/login@v2
      with:
        client-id:       ${{ secrets.CLIENTID }}
        tenant-id:       ${{ secrets.TENANTID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}

    - name: Collect static files
      run: python manage.py collectstatic --noinput
      env:
        AZURE_DEPLOYED: 'true'
        SECRET_KEY:                 ${{ secrets.SECRET_KEY }}
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

    - name: Apply database migrations
      run: python manage.py migrate --noinput
      env:
        AZURE_DEPLOYED: 'true'
        SECRET_KEY:                 ${{ secrets.SECRET_KEY }}
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
name: Build and deploy Python app to Azure Web App - MattsPortfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Run database migrations
        run: |
          source venv/bin/activate
          python manage.py migrate
        env:
          AZURE_DEPLOYMENT: 'true'
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}
          AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}

      - name: Run collectstatic
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput
        env:
          AZURE_DEPLOYMENT: 'true'
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}
          AZURE_CONTAINER: ${{ secrets.AZURE_STATIC_CONTAINER }}

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}
          federated-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'MattsPortfolio'
          slot-name: 'Production'
