name: Build and deploy Python app to Azure Web App - MattysWebsite

# Grant OIDC token ability
permissions:
  id-token: write    # ← MUST for azure/login to fetch a token
  contents: read     # ← to let you pull/check out your code

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create venv & install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Migrate DB
        env:
          AZURE_DEPLOYED: 'true'
          SECRET_KEY:       ${{ secrets.SECRET_KEY }}
          DB_HOST:          ${{ secrets.DB_HOST }}
          DB_PORT:          ${{ secrets.DB_PORT }}
          DB_NAME:          ${{ secrets.DB_NAME }}
          DB_USER:          ${{ secrets.DB_USER }}
          DB_PASSWORD:      ${{ secrets.DB_PASSWORD }}
          AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_KEY:  ${{ secrets.AZURE_ACCOUNT_KEY }}
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Collect static files
        env:
          AZURE_DEPLOYED: 'true'
          SECRET_KEY:       ${{ secrets.SECRET_KEY }}
          DB_HOST:          ${{ secrets.DB_HOST }}
          DB_PORT:          ${{ secrets.DB_PORT }}
          DB_NAME:          ${{ secrets.DB_NAME }}
          DB_USER:          ${{ secrets.DB_USER }}
          DB_PASSWORD:      ${{ secrets.DB_PASSWORD }}
          AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_KEY:  ${{ secrets.AZURE_ACCOUNT_KEY }}
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Zip and upload artifact
        run: zip -r release.zip ./* -x "venv/*"
      - uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-app

      - run: unzip release.zip

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name:  'MattysWebsite'
          slot-name: 'Production'
