name: Build and deploy Python app to Azure Web App – MattsPortfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Package up your source (but omit any local venv or caches)
      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./
            !venv/
            !**/__pycache__/
            !**/*.pyc

deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: Production
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  permissions:
    id-token: write

  steps:
    - name: Download source artifact
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id:     ${{ secrets.CLIENTID }}
        tenant-id:     ${{ secrets.TENANTID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}

    - name: Deploy code to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name:  'WA-Hilltop-Tuition-27042025'
        slot-name: 'Production'
        package:   .

    - name: Install dependencies & run migrations
      uses: azure/webapps-deploy@v3
      with:
        app-name:  'WA-Hilltop-Tuition-27042025'
        slot-name: 'Production'
        command: |
          cd /home/site/wwwroot

          python3 -m venv antenv
          source antenv/bin/activate

          pip install --upgrade pip \
            2>&1 | tee install.log
          pip install -r requirements.txt \
            2>&1 | tee -a install.log

          python manage.py makemigrations --verbosity 2 \
            2>&1 | tee makemigrations.log

          python manage.py migrate --verbosity 2 \
            2>&1 | tee migrate.log

          python manage.py showmigrations \
            2>&1 | tee showmigrations.log

          cat install.log makemigrations.log migrate.log showmigrations.log
