name: Deploy Django to Azure Web App

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.CLIENTID }}
          tenant-id:       ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name:  'MattysWebsite'
          slot-name: 'Production'
          package:   '.'
