name: Build & Deploy

on:
  push:
    branches: [ main ]

env:
  AZURE_DEPLOYED: true
  AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
  AZURE_ACCOUNT_KEY:  ${{ secrets.AZURE_ACCOUNT_KEY }}
  DB_NAME:            ${{ secrets.DB_NAME }}
  DB_USER:            ${{ secrets.DB_USER }}
  DB_PASSWORD:        ${{ secrets.DB_PASSWORD }}
  DB_HOST:            ${{ secrets.DB_HOST }}
  DB_PORT:            ${{ secrets.DB_PORT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations
      run: python manage.py migrate

    - name: Collect static files
      run: python manage.py collectstatic --noinput

    - name: Upload static to Azure Blob
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch \
            --account-name $AZURE_ACCOUNT_NAME \
            --account-key $AZURE_ACCOUNT_KEY \
            --destination static \
            --source hilltop_tuition/staticfiles \
            --overwrite \
            --no-progress

    - name: Package release
      run: zip -r release.zip ./* -x "venv/*"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: release.zip
