name: Build and deploy Python app to Azure Web App - MattysWebsite

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME:            ${{ secrets.DB_NAME }}
      DB_USER:            ${{ secrets.DB_USER }}
      DB_PASSWORD:        ${{ secrets.DB_PASSWORD }}
      DB_HOST:            ${{ secrets.DB_HOST }}
      DB_PORT:            ${{ secrets.DB_PORT }}
      AZURE_DEPLOYED:     "true"
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
      AZURE_ACCOUNT_KEY:  ${{ secrets.AZURE_ACCOUNT_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run database migrations
        run: python manage.py migrate

      - name: Debug Django static settings
        run: |
          python3 - <<'EOF'
          import os, django
          from django.conf import settings
          os.environ.setdefault('DJANGO_SETTINGS_MODULE','hilltop_tuition.settings')
          django.setup()
          print("AZURE_DEPLOYED =", settings.AZURE_DEPLOYED)
          print("STATICFILES_STORAGE =", settings.STATICFILES_STORAGE)
          print("AZURE_ACCOUNT_NAME =", settings.AZURE_ACCOUNT_NAME)
          print("AZURE_ACCOUNT_KEY =", bool(settings.AZURE_ACCOUNT_KEY))
          EOF

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Upload static & media to Azure Blob
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ env.AZURE_ACCOUNT_NAME }} \
              --account-key  ${{ env.AZURE_ACCOUNT_KEY  }} \
              --destination static \
              --source      hilltop_tuition/staticfiles \
              --no-progress

            az storage blob upload-batch \
              --account-name ${{ env.AZURE_ACCOUNT_NAME }} \
              --account-key  ${{ env.AZURE_ACCOUNT_KEY  }} \
              --destination media \
              --source      media/tutors \
              --no-progress

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x "venv/*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_WEBAPP_CLIENTID }}
          tenant-id:       ${{ secrets.AZURE_WEBAPP_TENANTID }}
          subscription-id: ${{ secrets.AZURE_WEBAPP_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MattysWebsite'
          package: .
