name: Deploy static assets to Azure Blob Storage

on:
  push:
    paths:
      - 'home/templates/**'
      - 'home/static/**'
      - 'media/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    env:
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
      AZURE_ACCOUNT_KEY:  ${{ secrets.AZURE_ACCOUNT_KEY }}
      STATIC_CONTAINER:   static
      MEDIA_CONTAINER:    media
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_WEBAPP_CLIENTID }}
          tenant-id:       ${{ secrets.AZURE_WEBAPP_TENANTID }}
          subscription-id: ${{ secrets.AZURE_WEBAPP_SUBSCRIPTIONID }}

      - name: Upload HTML/CSS/JS
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name $AZURE_ACCOUNT_NAME \
              --account-key  $AZURE_ACCOUNT_KEY \
              --destination $STATIC_CONTAINER \
              --source      home/templates \
              --no-progress \
              --overwrite

            az storage blob upload-batch \
              --account-name $AZURE_ACCOUNT_NAME \
              --account-key  $AZURE_ACCOUNT_KEY \
              --destination $STATIC_CONTAINER \
              --source      home/static \
              --no-progress \
              --overwrite

      - name: Upload media images
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name $AZURE_ACCOUNT_NAME \
              --account-key  $AZURE_ACCOUNT_KEY \
              --destination $MEDIA_CONTAINER \
              --source      media \
              --no-progress \
              --overwrite
